spec/basic.md
Well, if we all agree on how it should be done. Why not to fill the gap in spec, right?
Closes #142
=> Added more description to subscribing section

spec/advanced.md
=> The caller specifies timeouts

rfc/draft-oberstet-hybi-tavendo-wamp.xml, rfc/text/advanced/ap_rpc_progressive_call_results.md
An invocation message has a details field not an options field.
=> Fixed typo

rfc/text/basic/bp_transports.md
Added references to WS RFC to make navigating a bit more convenient.
=> Add links / reference to WS proto.

rfc/draft-oberstet-hybi-tavendo-wamp.html, rfc/draft-oberstet-hybi-tavendo-wamp.txt, rfc/draft-oberstet-hybi-tavendo-wamp.xml
Before: ... can cancel and issued call ...
After:   ... can cancel an issued call ...
Also some end of line whitespace was removed
=> Fix typo in the RFC

rfc/text/advanced/ap_pubsub_event_retention.md
See https://github.com/wamp-proto/wamp-proto/issues/261
cc @oberstet
=> Initial event retention draft

rfc/draft-oberstet-hybi-tavendo-wamp.md, rfc/text/advanced/ap_pubsub_testament.md
Here's a draft... cc @oberstet 
Fixes #266
=> Last Will/Testament

rfc/text/advanced/ap_rpc_call_canceling.md
Guys, i've updated spec, based on our discussions. Please have a look, and may be even merge if it is ok :)
I think we should always use Pull requests with minimum one man review for updating spec.
=> Described call canceling. closes #140. closes #141.

rfc/text/basic/bp_identifiers.md
Fix issue #231
It tightens the definition of identifier for the basic profile
=> Fix issue #231

rfc/text/basic/bp_sessions.md, rfc/text/basic/bp_transports.md, rfc/text/basic/bp_uris.md
Hopefully closes #108.
Guys, please take a look at this. Is it ok? What do you think?
=> Described protocol violation errors and cases

rfc/text/advanced/ap_rpc_pattern_based_registration.md
Tried to combine all our thoughts and extend it with examples.
Refs #182
=> Described pattern-based RPC call routing

rfc/text/advanced/ap_rpc_pattern_based_registration.md
Fix some spelling, grammar, and consistency issues.
=> Minor editing tweaks

rfc/text/advanced/ap_rpc_pattern_based_registration.md
=> Fixed long lines in pattern-based registrations. Closes #307

rfc/text/advanced/ap_pubsub_subscription_revocation.md, rfc/text/advanced/ap_rpc_registration_revocation.md
I tried to describe which how those features work.
If anyone can decide how exactly we want to do the feature announcement for this, I'm happy to update this PR.
=> Document how subscription/registration revokation works

docs/routing.rst
I've refactored links on routing page, hope it'll looks fine :)
=> Edits to routing.rst links

rfc/text/basic/bp_pubsub_publishing_and_events.md, rfc/text/basic/bp_rpc_calling_and_invocation.md, rfc/text/basic/bp_rpc_registering_and_unregistering.md
=> Correct description of request ID scope.

rfc/text/advanced/ap_rpc_pattern_based_registration.md
=> Correct RPC wildcard match example

docs/implementations.rst
Moving the repositories around a bit as I make room for the router implementation
=> updates the title, description and link to the WAMPexClient library

docs/implementations.rst
=> Add connectanum-dart, fix connectanum link

docs/implementations.rst
This implementation is not feature-complete, but it is in a usable state for pet-projects. I am going to contribute to the project while building my pet-projects using it.
=> Add asynchronous WAMP client library implementation in Rust

rfc/aux/header.html
A small update to w3c spec builder: fixed errors and warnings. Hope it will works as expected :)
=> A few updated to w3c respec build: fixed warnings

.travis-deploy.sh, rfc/aux/header.html
Fixed logo url 
And hope it wil fix the build and deploy for w3c spec
=> Some fixes for w3c spec

rfc/text/advanced/ap_09_rpc_progressive_call_results.md, rfc/text/advanced/ap_10_rpc_progressive_calls.md, rfc/text/advanced/ap_48_uris.md, rfc/wamp-ap.md, rfc/wamp-bp.md, rfc/wamp.md
Here is a draft with description of progressive call.
=> RPC progressive calls

rfc/text/advanced/ap_02_features.md
Please see description in #415
=> Updated feature statuses. 

rfc/text/advanced/ap_50_payload_passthru_mode.md
I've started implementing ppt feature and faced a few inaccuracies in spec. 
Fixed some misconceptions and added more description to ppt mode example schemas.
=> Fixed ppt examples schemas and messages

rfc/text/advanced/ap_11_rpc_call_timeout.md, rfc/text/advanced/ap_48_uris.md
Resolves #155
Pinging those who commented in the related issue: @estan @gammazero @oberstet
=> Specify Call Timeouts More Clearly

rfc/text/advanced/ap_09_rpc_progressive_call_results.md, rfc/text/advanced/ap_10_rpc_progressive_calls.md
Pinging @oberstet and @KSDaemon who commented in the related issues.
=> Frozen Progressive Call options and Progressive Call Results timeouts

rfc/text/advanced/ap_10_rpc_progressive_calls.md
Reverts wamp-proto/wamp-proto#458
=> Revert "Removed sticky option from progressive calls"

rfc/text/advanced/ap_10_rpc_progressive_calls.md
Reverts wamp-proto/wamp-proto#460
=> Revert "Remove sticky"

rfc/text/advanced/ap_38_transport_rawsocket.md
Adding CBOR to RawSocket like https://wamp-proto.org/wamp_latest_ietf.html#section-2.2-6 and https://wamp-proto.org/wamp_latest_ietf.html#section-2.3.1-4.
=> Add CBON, UBJSON and FlatBuffers to RawSocket

rfc/text/advanced/ap_09_rpc_progressive_call_results.md, rfc/text/advanced/ap_10_rpc_progressive_call_invocations.md, rfc/text/advanced/ap_48_uris.md, rfc/text/basic/bp_06_remote_procedure_call.md, rfc/text/basic/bp_08_uri_reference.md
Resolves #476 and #477
Pinging @oberstet @KSDaemon @Jopie64 for review
=> Consolidate/clarify caller/callee leaving behavior

rfc/text/advanced/ap_10_rpc_progressive_call_invocations.md
Fixes #482
Pinging @Jopie64 , @KSDaemon , @oberstet for review.
=> Contuations on completed progressive calls

docs/implementations.rst
Hi folks! I've finally published Wampy cli tool! So it is good idea to add it to corresponding section on the site :)
Also, updated wampy client description as the old one is no longer valid and was outdated...
=> Added wampy cli to implementations tool section

rfc/text/advanced/ap_11_rpc_call_timeout.md
Fixes #500.
Pinging @Jopie64 who commented in the related issue. Anyone else is welcome to comment/review of course.
=> REGISTER.Options.forward_timeout option

rfc/text/advanced/ap_14_rpc_caller_identification.md, rfc/text/advanced/ap_23_pubsub_publisher_identification.md
=> Specify disclosed properties

rfc/text/basic/bp_03_messages.md, rfc/text/basic/bp_04_sessions.md, rfc/text/basic/bp_08_uri_reference.md
=> Abort with payload

rfc/text/advanced/ap_38_transport_rawsocket.md
=> Fix raw socket maximum length limit

rfc/text/basic/bp_03_messages.md, rfc/text/basic/bp_04_sessions.md
No content change, remove a single quote, and reformat message table
=> minor changes

rfc/text/basic/bp_02_building_blocks.md
=> Explicit behavior when session scope overflow.

rfc/text/advanced/pubsub_subscriber_blackwhite_listing.md, rfc/text/advanced/router_to_router_links.md, rfc/text/basic/publish_subscribe.md, rfc/text/wamp-terminology.md
=> Only grammar fix for render.

rfc/text/advanced/features.md
My last PR today, it's time 2:50 a.m. in my timezone (UTC+08:00) now.
Leave one discuss here:
I want to resort AP's chapter orders in:
1. Session
2. PubSub
3. RPC
Both sections and this table, how do you think?
=> Fill full columns name, and remove unrelated column.

rfc/text/advanced/pubsub_publisher_identification.md, rfc/text/advanced/rpc_caller_identification.md
That was likely overlooked when writing.
=> Use correct error message format when dealer/broken dont support disclose_me

rfc/text/advanced/rpc_pattern_based_registration.md
Current text said "longest one", but not clear which length ("full pattern" or "first portion")
=> Disambiguate which is the "longest one".

.github/workflows/build-and-test.yml, .github/workflows/deploy-to-gh-pages.yml, docs/conf.py, docs/implementations.rst
This PR adds a list of WAMP implementations of client & router in the following languages:
1. Go (Router & client).
2. Dart/Flutter.
3. Python.
4. Swift.
5. Rust.
6. Kotlin.
7. TypeScript.
=> docs: add `xconn` libraries to list of implementations
