spec/advanced.md

The handshake error and framing illustrations were missing an octet.

Add missing octets in RawSocket ASCII illustrations

---

website/wampws/templates/page_t_implementations.html

Putting "yes" in the column for "Advanced Profile" seems presumptious since we don't support the majority of features in the Advanced Profile, but "no" also sounds wrong because some are there (rawsocket, call timeouts). So I put "some" in that column. Hope that works.

Add Bonefish to the list of WAMP (v2) router implementations.

---

spec/advanced.md

For example, when the dealer is processing an incoming call message
from the caller, the dealer has to send an invocation message to the
callee. If there is a network failure when trying to send the
invocation message we need to send an error response back to the
callee so that it can respond accordingly. Otherwise, the caller
will be blocked waiting for an invocation response which will never
arrive.

Add a predefined error uri for network failures.

---

rfc/draft-oberstet-hybi-tavendo-wamp-00.md

Reviewed and edited for the quality of English prose. I have not attempted to change the meaning of anything.
My line notes are for the line **immediately above**.

Introduction - spelling, grammar, and prose

---

rfc/STATUS.md

Fix spec status legend table in STATUS.md

---

rfc/draft-oberstet-hybi-tavendo-wamp.md

I believe this should only be included once? (Above, under authentication `ap_authentication.md`)

Remove stray inclusions of ticked based auth section

---

rfc/text/basic/bp_sessions.md
rfc/text/basic/bp_transports.md

This commit explicitly defines what protocol errors are and what
peers shall do when those happen.

(#255) Fix lack of specification

---

rfc/text/advanced/ap_pubsub_subscription_meta_api.md
rfc/text/advanced/ap_rpc_registration_meta_api.md

Hi! Just added a clear note, that meta events payload consists of positional arguments.

Updated META APIs with events payload description

---

rfc/text/advanced/ap_authentication_cra.md

Example shows what appears to be a base64-encoded string in the CRA response, but the format needs to be explicitly stated.

Explicitly state format of signature string

---

rfc/text/basic/bp_sessions.md
rfc/text/basic/bp_uris.md

As we all agreed in #192 . Moved GOODBYE URIs to `close` namespace.

Added special namespace for GOODBYE messages

---

rfc/text/advanced/ap_session_meta_api.md

This change documents four new meta procedures for the session meta API:
- wamp.session.kill
- wamp.session.kill_by_authid
- wamp.session.kill_by_authrole
- wamp.session.kill_all
Fixes issue #314

Describe wamp.session.kill meta procedures

---

rfc/text/advanced/ap_session_meta_api.md

Fixes #238 by providing additional arguments in wamp.session.on_leave event.

Additional arguments for wamp.session.on_leave

---

rfc/draft-oberstet-hybi-crossbar-wamp.md
rfc/text/advanced/ap_rpc_call_timeout.md
rfc/text/basic/bp_pubsub_publishing_and_events.md

Just some clarifying changes.
- The description for section 9 (Publish and Subscribe) says that it defines implementation details for a *dealer* where it should say *broker*. It even says it's for a *broker* in the next sub-section.
- A couple of grammar and sentence rearrangements

Fix typos and clarify some grammar

---

docs/implementations.rst

The only current implementation of WAMP for PHP is Thruway made using asynchronous React event loop, which is for example hard to use in classic-synchronous PHP code.
Here is a small library with minimal dependencies that allow for two line call to remote WAMP procedures as well as publish WAMP events.

add WampSyncClient to implementations

---

rfc/text/basic/bp_messages.md

I thought maybe the 25 was also including the Advanced messages, but there are only 4 of those and the surrounding text here clearly refers to the Basic messages. Or did I miss something?

Fix number of messages in bp_messages.md

---

docs/implementations.rst

Adds WAMPex to the list of client implementations. WAMPex is a pure Elixir implementation of a WAMP client.

Add WAMPex

---

docs/comparison.rst

The original link to "Web Technologies for the Internet of Things" is dead.  I've found a working uri.

Update "Web Technologies for the Internet of Things" link

---

docs/routing.rst
rfc/text/advanced/ap_rpc_registration_meta_api.md
rfc/text/advanced/ap_rpc_shared_registration.md
rfc/text/basic/bp_pubsub_publishing_and_events.md
rfc/text/basic/bp_pubsub_subscribing_and_unsubscribing.md
rfc/text/basic/bp_rpc_calling_and_invocation.md
rfc/text/basic/bp_rpc_registering_and_unregistering.md
rfc/text/basic/bp_sessions.md

Pretty simple, just corrected the grammar for a few of the doc pages. Swapped any reference of `an URI` for `a URI`.
Thanks to those of you working on this! My addition is peanuts in comparison.

Editorial Correction - "an URI" for "a URI"

---

rfc/text/advanced/ap_uris.md

Callee black-white listing is not a feature in WAMP, yet this error message
implies that it is.  This PR fixes Issue #342

Remove error message that implies callee black-white listing

---

docs/implementations.rst

On  Routers section of Implementations page, there was an excess tag of <td> on wamprt table item. This commit removes that tag and corrects the visibility.

Remove excess HTML tag <td> from documentation

---

rfc/text/advanced/ap_10_rpc_progressive_calls.md

Fixed copy paste :) 
As options is called `progress` rather then `progressive_calls` (which is a feature naming)

Fixed progressive call option naming in spec

---

rfc/text/advanced/ap_02_features.md

I think Event history feature is well defined now in the spec and there is at least one and half implementations :)
So lets set status to `beta`. When XB will be aligned with the spec we can set it to stable, as there will be 2 broker implementations already.

Changed event history feature status alpha->beta

---

rfc/text/basic/bp_05_publish_subscribe.md

Event message's parameter name should be Argument[s]Kw.

Fix misspelled parameter name.

---

rfc/text/basic/bp_05_publish_subscribe.md

Other messages' which generate request ID are all using session scope sequential ID, should SUBSCRIBE/UNSUBSCRIBE message using sequential ID too?

SUBSCRIBE and UNSUBSCRIBE's request id sequential

---

rfc/text/basic/bp_02_building_blocks.md

As discussed in #436 , adding message with non-sequential request ID to [protocol errors](https://wamp-proto.org/wamp_latest_ietf.html#name-protocol-errors) scenarios.

Add non-sequential request ID to Protocol errors

---

rfc/text/advanced/ap_10_rpc_progressive_calls.md

All mentions of Progressive Call Results have been consolidated to its own sub-section. This makes it easier to understand the fundamentals of Progressive Calls before mixing in Progressive Call Results.
I added the missing requirement that Callees must announce the `call_cancelling` feature.
I also took the liberty of enhancing the English grammar and style while leaving the technical requirements intact.

Consolidate progress call results stuff and clarify progressive calls language

---

rfc/text/advanced/ap_09_rpc_progressive_call_results.md

Encountered typo while reading part of the docs.

Fix typo in progressive call results doc

---

rfc/text/advanced/ap_48_uris.md
rfc/text/basic/bp_01_introduction.md

this PR is supposed to consolidate and cleanup the discussion from https://github.com/wamp-proto/wamp-proto/pull/444 and supersedes the latter
The PR adds:
1. the URIs and descriptions from the discussion above - hopefully
2. it also adds `no_auth_method`, `no_such_realm`, `no_such_role` and `no_such_principal`
I have done 2. after reviewing this whole new section and after reviewing auth code in crossbar/autobahn code. It is necessary there, and I think it makes sense, *but I can remove that again and only keep 1!*. Let me know.

[WIP] AA related URIs

---

rfc/text/advanced/ap_05_meta_api_sessions.md
rfc/text/advanced/ap_48_uris.md

Use wamp.close.killed when session forcefully killed via meta API

---

rfc/text/advanced/ap_10_rpc_progressive_call_invocations.md

As requested by @Jopie64 and drafted by @KSDaemon .

Clarify rationale for Callee ignoring obsolete progressive invocations

---

_work/predefined-uris.md
docs/comparison.rst
rfc/text/advanced/ap_10_rpc_progressive_call_invocations.md
rfc/text/advanced/ap_12_rpc_call_canceling.md
rfc/text/advanced/ap_16_rpc_pattern_based_registration.md
rfc/text/advanced/ap_48_uris.md
rfc/text/basic/bp_04_sessions.md
rfc/text/basic/bp_08_uri_reference.md

Replaced all `NBSP` (that results in (U+00A0) after rendering) with just spaces. So now the spec should look clean

Replaced all NBSP with spaces

---

rfc/text/advanced/ap_10_rpc_progressive_call_invocations.md

Elaborate on subsequent progressive invocation options

---

rfc/wamp-ap.md
rfc/wamp-bp.md
rfc/wamp.md

Why not include the terminology into the full specification?

Adding terminology page into full spec.

---

rfc/text/basic/bp_03_messages.md

As [Section-4.1.3](https://wamp-proto.org/wamp_latest_ietf.html#section-4.1.3) said:
> Both the Router and the Client may abort a WAMP session by sending an ABORT message.

Client may abort a WAMP session by sending an ABORT message.

---

rfc/text/basic/building_blocks.md

Need discuss.
Current spec not point what if dealer received a YIELD message, but its INVOCATION.Request is not issued by the dealer.
My point is to ABORT the session because it should be treat as MALFORMED message like non-sequential request ID.

ABORT a session if received YIELD msg w/ invalid INVOCATION.Request

---

rfc/text/advanced/authorization.md
rfc/text/basic/messages.md
rfc/text/basic/remote_procedure_call.md

1. Changes `*Session*s` to `*Sessions*`;
2. Replace unicode `—` to ascii `-`;
3. Remove accident space and asterisk, insert missing space.

Typo and grammar fix.

---

docs/implementations.rst

This pull requests adds [wamplv](https://github.com/samangh/wamplv) to the list of WAMP client applications. This is a WAMP client written in LabVIEW, a data-flow driven language mostly used in the experimental sciences, engineering, robotics and real-time industrial control systems.
It would be great if we could include this in the implementation list, as far as I'm aware there are no other LabVIEW implementations of WAMP.

Add `wamplv` to list of client implementations
